@startuml
'https://plantuml.com/object-diagram



map Wallet {
 Registration =>
 WithDraw =>
 Top-Up =>
 Transfer =>
}

map Marketplace {
 List =>
 Purchase =>
 Agree =>
 Confirm =>
 Sort =>
}


map Registration{
    Register =>
    Login =>
    CreateWallet =>
}

map Project {
 Branch *---> Marketplace
 Branch *---> Wallet
 Branch *---> Registration
}


@enduml
