@startuml
'https://plantuml.com/object-diagram

map Adv{
  Issuer => AdvOffer.Issuer
  Advertiser => AdvRequest.Issuer
  State => Init/PendingCost/PendingAdv/Done/Closed
}


map AdvRequest {
 Adverts *--> Adv
 Media => Png/Jpeg/Mp4
 Name => string
 Link to place => string
 Description => string
 Place => string
 Price => int
 Issuer => UserAdvertiser
}

map AdvOffer {
 Advert *--> Adv
 Media => Png/Jpeg/Mp4
 Name => string
 Link to place => string
 Description => string
 Place => string
 Price => int
 Issuer => UserInfluencer
}

map Wallet {
 Registration =>
 WithDraw =>
 Top-Up =>
 Transfer =>
}

map Marketplace {
 Adverts *---> AdvOffer
 Adverts *---> AdvRequest
 List =>
 Purchase =>
 Agree =>
 Confirm =>
 Sort =>
}


map Registration{
 FirstName => string
 LastName => string
 Username => string
 ProfileImage => Png/Jpeg
 BannerImage => Png/Jpeg
 SocialMediaLinks => []string
}

map Project {
 Branch *---> Marketplace
 Branch *---> Wallet
 Branch *---> Registration
}


@enduml
